### ISSUE TITLE
Install app not showing

### ISSUE THREAD

**Issue by AdditionAddict** [umluizlima/flask-pwa#3]
Install app not showing on heroku, both for demo and when I've tried this myself

**Comment by raghavendrajain** [comment]
I face the same issue. For me the "Install App" button is being shown when I use Ubuntu OS, but it is not shown when I am on Windows 10 or iPhone 7+.

**Comment by umluizlima** [comment]
Hi, @AdditionAddict ! Can you provide more details about device and browser? Also, were you on incognito mode?

I've tested it on Chrome (Android and Windows 10) and it seems to work just fine.

**Comment by umluizlima** [comment]
Hello, @raghavendrajain ! What browser are you using on either platforms?

**Comment by pastorhudson** [comment]
It works for me on Ubuntu using Chrome.
Install button disappeared once the app was installed.

Install button does not work on iOS for Safari or Chrome, but that's to be expected. The add to homescreen sharesheet created the icon and looked quite nice. It launced from the icon just fine.

**Comment by raghavendrajain** [comment]
> Hello, @raghavendrajain ! What browser are you using on either platforms?

Hi @umluizlima I used Chrome for iOS and also Safari for iOS. It did not work. Works for Chrome on Ubntu though.

**Comment by raghavendrajain** [comment]
> It works for me on Ubuntu using Chrome.
> Install button disappeared once the app was installed.
> 
> Install button does not work on iOS for Safari or Chrome, but that's to be expected.

Hi @pastorhudson, can you please clarify that why this behavior is to be expected!

**Comment by pastorhudson** [comment]
@raghavendrajain Apple doesn’t let us install Progressive Web Applications using an install button. They are pretty guarded and want everything to go through the App Store.

They do allow adding “shortcuts” by tapping the share button and then tapping add to home screen.

Before there was an App Store this is how you installed apps on iOS.

The shortcut is more than a shortcut though and can be a quite capable PWA.

It’s annoying because this means extra steps for our users, but I don’t see Apple changing this anytime soon.

Edit: It only works in safari. Apple doesn’t allow other browsers to install PWA on iOS.

**Comment by raghavendrajain** [comment]
@pastorhudson  Thank you very much Ron. That helps. BTW, I have a question _unrelated_ to this webapp but related to PWA on iOS.  My PWA uses a model trained using machine learning and the model itself rests on the remote server. But I want to give my users an option to download the AI model (it is a file of about 50~70 MB) directly on their phones. 

my question is:  
How to manage file download/storage on iOS for a flask pwa application? 

Many thanks in advance.

**Comment by pastorhudson** [comment]
@raghavendrajain i just saw this. Did you figure it out? It would be cool to hear how you did this.

**Comment by AdditionAddict** [comment]
Apologies for not following up on this - my question was based on misunderstanding expected behaviour as explained above - feel free to close issue.
