### ISSUE TITLE
CLI No exception error

### ISSUE THREAD

**Issue by aipladmin** [umluizlima/flask-pwa#4]
Greetings,
When I tried to access the site by using `flask run` it throws an error saying:
` flask.cli.NoAppException: Failed to find Flask application or factory in module "analyticaldashboard.app". Use "FLASK_APP=analyticaldashboard.app:name to specify one. `

analyticaldashboard is the name of my folder where all the files resides

Thank you

**Comment by SmartManoj** [comment]
set FLASK_APP=analyticaldashboard.app:name

**Comment by aipladmin** [comment]
Thanxs @SmartManoj
