### ISSUE TITLE
Unable to install on heroku 

### ISSUE THREAD

**Issue by theofficialvkr** [umluizlima/flask-pwa#5]
Error log { -----> Installing pip 20.2.4, setuptools 47.1.1 and wheel 0.36.2

-----> Installing dependencies with Pipenv 2020.11.15

       Installing dependencies from Pipfile.lock (72b22b)...

       An error occurred while installing markupsafe==1.0 --hash=sha256:a6be69091dac236ea9c6bc7d012beab42010fa914c459791d627dad4910eb665! Will try again.

       Installing initially failed dependencies...

       [InstallError]:   File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/cli/command.py", line 253, in install

       [InstallError]:       site_packages=state.site_packages

       [InstallError]:   File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/core.py", line 2063, in do_install

       [InstallError]:       keep_outdated=keep_outdated

       [InstallError]:   File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/core.py", line 1312, in do_init

       [InstallError]:       pypi_mirror=pypi_mirror,

       [InstallError]:   File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/core.py", line 900, in do_install_dependencies

       [InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs

       [InstallError]:   File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/core.py", line 796, in batch_install

       [InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)

       [InstallError]:   File "/app/.heroku/python/lib/python3.6/site-packages/pipenv/core.py", line 703, in _cleanup_procs

       [InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)

       [pipenv.exceptions.InstallError]: Looking in indexes: https://pypi.python.org/simple

       [pipenv.exceptions.InstallError]: Collecting markupsafe==1.0

       [pipenv.exceptions.InstallError]:   Using cached MarkupSafe-1.0.tar.gz (14 kB)

       [pipenv.exceptions.InstallError]:     ERROR: Command errored out with exit status 1:

       [pipenv.exceptions.InstallError]:      command: /app/.heroku/python/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dakrb5mg/markupsafe/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dakrb5mg/markupsafe/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vwakgvlc

       [pipenv.exceptions.InstallError]:          cwd: /tmp/pip-install-dakrb5mg/markupsafe/

       [pipenv.exceptions.InstallError]:     Complete output (5 lines):

       [pipenv.exceptions.InstallError]:     Traceback (most recent call last):

       [pipenv.exceptions.InstallError]:       File "<string>", line 1, in <module>

       [pipenv.exceptions.InstallError]:       File "/tmp/pip-install-dakrb5mg/markupsafe/setup.py", line 6, in <module>

       [pipenv.exceptions.InstallError]:         from setuptools import setup, Extension, Feature

       [pipenv.exceptions.InstallError]:     ImportError: cannot import name 'Feature'

       [pipenv.exceptions.InstallError]:     ----------------------------------------

       [pipenv.exceptions.InstallError]: ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

       ERROR: Couldn't install package: markupsafe

        Package installation failed...

 !     Push rejected, failed to compile Python app.

 !     Push failed    }

what are the buildpack required to install it .

**Comment by pastorhudson** [comment]
It looks like your issue is with the package markupsafe. Perhaps try pinning to a newer version? MarkupSafe is currently at 1.1.1
